// Team codex UI text in English and Thai. Spec content (markdown from wcmmo-specs) stays in
// English; status keywords (DRAFT, DONE, OPEN, D-xx…) stay as-is because they are spec terms.
import type { Dict } from '../shared/i18n'

const en = {
  nav: { overview: 'Overview', specs: 'Specs', graph: 'Graph', decisions: 'Decisions', roadmap: 'Roadmap', questions: 'Questions', plugins: 'Plugins', library: 'Library' },
  layout: { skip: 'Skip to content', menu: 'Menu', signOut: 'Sign out', publicSite: 'Public site', teamCodex: 'Team codex', footer: 'WC-MMO team codex · internal', syncedFrom: 'Synced from' },
  englishSource: '',
  common: { all: 'All', clear: 'Clear', search: 'Search', openOnGithub: 'Open on GitHub ↗', noneYet: 'none yet', updated: 'updated' },
  dash: {
    kicker: 'Classless action MMORPG · Purpur 26.2',
    title: 'WC-MMO Codex',
    intro: 'Every spec, decision and proof-of-concept from',
    intro2: ', read straight from the repo and charted by progress.',
    browse: 'Browse specs',
    graph: 'Dependency graph',
    lastCommit: (a: string, b: string) => `Last spec commit ${a} · synced ${b}`,
    slice: 'Vertical slice',
    days: (n: number) => `${n} days`,
    toEarly: 'to the 2-week mark',
    toLate: 'to the 3-week mark',
    passed: 'Window passed',
    start: 'Start',
    wk2: '2 wk',
    wk3: '3 wk',
    dayOf: (d: number, t: number) => `Day ${d} of ${t}. Scope re-check at the end of week 1 (TM3).`,
    tiles: { specsDone: 'Specs done', decisions: 'Decisions made', stillOpen: (n: number) => `${n} still open`, pocs: 'PoCs proven', acceptance: 'Acceptance checks', questions: 'Owner questions', pending: 'pending answers' },
    pipeline: 'Spec pipeline',
    allSpecs: 'All specs →',
    pipelineHelp1: 'DRAFT → READY → IN-PROGRESS → DONE. A spec can’t move to READY while a decision it cites is still open, so the count next to each draft is its blocker count.',
    pipelineHelp2: (n: number) => `${n} drafts cite no open decisions and only need their sections finished.`,
    open: (n: number) => `${n} open`,
    unblocked: 'unblocked',
    byArea: 'Decisions by area',
    decisionsLink: 'Decisions →',
    blocks: 'What blocks each spec',
    graphLink: 'Graph →',
    blocksHelp: 'Open decisions cited per unfinished spec. Click a bar to open the spec.',
    phases: 'Phases',
    roadmapLink: 'Roadmap →',
    phase: (n: number, name: string) => `Phase ${n}: ${name}`,
    nSpecs: (n: number) => `${n} specs`,
    notSpecced: 'not specced',
    pocs: 'Phase 0 PoCs',
    activity: 'Specs repo activity',
    recent: 'Recent',
    commit: 'commit',
    decision: 'decision',
    lastSynced: (d: string) => `Specs repo last synced ${d}.`,
  },
  charts: { decided: 'Decided', partly: 'Partly / testing', open: 'Open', blocking: 'Blocking', openDecisions: ' open decisions', added: 'Lines added', removed: 'Lines removed' },
  specs: {
    kicker: 'Quest log',
    title: 'Specs',
    intro1: 'One card per',
    intro2: '. Filters live in the URL, so you can share a view.',
    placeholder: 'title, story, repo, D-xx…',
    status: 'Status',
    phase: 'Phase',
    repo: 'Repo',
    blocked: 'Blocked',
    hasOpen: 'Has open decisions',
    unblocked: 'Unblocked',
    count: (n: number, t: number) => `${n} of ${t} specs`,
    none: 'No spec matches these filters.',
    blockedBy: (n: number) => `Blocked by ${n} open decision${n > 1 ? 's' : ''}`,
    openQ: (n: number) => `${n} open question${n > 1 ? 's' : ''}`,
    acceptance: 'Acceptance criteria',
  },
  spec: {
    doneMeans: 'Done means:',
    phase: 'Phase',
    repos: 'Target repos',
    fire: 'FIRE mode',
    acceptance: 'Acceptance criteria',
    log: 'Implementation log',
    runs: (n: number) => `${n} run${n > 1 ? 's' : ''} logged`,
    notBuilt: 'nothing built yet',
    lastChange: 'Last change',
    decisions: 'Decisions',
    nOpen: (n: number) => `(${n} open)`,
    pocs: 'Proof-of-concepts',
    linked: 'Linked specs',
    mentions: 'Mentions',
    mentionedBy: 'Mentioned by',
  },
  phases: { foundation: 'Foundation', unphased: 'Unphased', phase: (n: number, name: string) => `Phase ${n}: ${name}` },
  decisions: {
    kicker: 'GDD v2',
    title: 'Decisions',
    intro: 'Every D-xx in the design doc with its recommendation, the owner’s call, and the specs that depend on it. Specs can’t go READY while one of their decisions is open.',
    search: 'Search decisions…',
    options: 'Options: ',
    recommendation: 'Recommendation · ',
    ownersCall: 'Owner’s call · ',
    status: 'Status: ',
    citedBy: 'Cited by',
    none: 'No decision matches.',
    log: 'Decision log',
  },
  graph: {
    kicker: 'Work map',
    title: 'Dependency graph',
    intro: 'Phases → specs → the decisions they cite → the PoCs that settle them. Moving dashed lines are open decisions. Click any card to trace its links; scroll to pan, pinch or ⌘/Ctrl + scroll to zoom.',
    legend: { done: 'Done / decided / pass', open: 'Draft / open', partly: 'Partly', testing: 'Testing / fallback', pending: 'Pending PoC' },
    openOnly: 'Open decisions only',
    clear: 'Clear selection',
    columns: 'Columns',
    col1: 'Phases from spec 004',
    col2: 'Specs, coloured by status',
    col3: (a: number, b: number) => `Decisions they cite (${a} of ${b})`,
    col4: 'Phase 0 PoCs that settle them',
    select: 'Select a card to see its neighbours and details.',
    blocksReady: (n: number) => (n ? `${n} open decision(s) block READY.` : 'No open decisions cited.'),
    openSpec: 'Open spec ▶',
    openDecision: 'Open decision ▶',
    roadmap: 'Roadmap ▶',
    pass: 'Pass: ',
    nSpecs: (n: number) => `${n} specs`,
    loading: 'Loading graph…',
  },
  roadmap: {
    kicker: 'Spec 004',
    title: 'Roadmap',
    intro1: 'Prove the risky tech first (Phase 0), then ship a small playable slice. Everything here is read from',
    window: 'Vertical slice window',
    today: 'today',
    recheck: 'scope re-check',
    legend: 'Gold ring = today · orange underline = end of week 1 scope re-check (TM3) · green = 2-week target, gold = 3-week stretch.',
    phases: 'Phases',
    phase: (n: number) => `Phase ${n}`,
    exit: 'Exit: ',
    notSpecced: 'Not specced yet.',
    pocs: 'Phase 0 proof-of-concepts',
    passWhen: 'Pass when',
    fallback: 'Fallback',
    notes: (d: string) => `Result notes (${d})`,
    prereqs: 'Prerequisites before any PoC',
    progress: 'Progress log & next steps',
  },
  questions: {
    title: 'Open questions',
    intro: 'What the team is waiting on. When an answer arrives it moves to Answered, then the GDD decision, then the specs that cite it.',
    pending: (n: number) => `${n} pending`,
    answered: 'answered',
    pluginFill: 'Plugin details still to fill',
    pluginsLink: 'Plugins →',
    answeredTitle: 'Answered',
    total: (n: number) => `${n} questions pending in total.`,
  },
  plugins: {
    title: 'Plugins',
    intro1: 'The server’s plugin stack and where each one stands. Full notes per plugin are in the',
    guide: 'plugin guide',
    headers: ['Plugin', 'Category', 'Status', 'Version', '26.2', 'Used for', 'Specs'],
    legend: '26.2: ✅ store page says it supports 26.2 · ❓ not confirmed · ⚠️ store page shows an older max version.',
  },
  library: {
    kicker: 'Reading room',
    title: 'Library',
    intro: 'The design doc, briefs, registries and ADRs, rendered from the specs repo.',
    groups: { Design: 'Design', Brief: 'Brief', Registry: 'Registry', ADR: 'Architecture decisions' },
    specsLive: (n: number) => `${n} specs live under`,
    note: (n: string) => `This document is ${n}.`,
    boards: 'Concept boards',
  },
  notFound: { title: 'This path leads into the void', body: 'The page or spec isn’t in the synced specs repo.', back: 'Back to the Codex' },
}

type Strings = typeof en

const th: Strings = {
  nav: { overview: 'ภาพรวม', specs: 'สเปก', graph: 'กราฟ', decisions: 'การตัดสินใจ', roadmap: 'โรดแมป', questions: 'คำถาม', plugins: 'ปลั๊กอิน', library: 'คลังเอกสาร' },
  layout: { skip: 'ข้ามไปยังเนื้อหา', menu: 'เมนู', signOut: 'ออกจากระบบ', publicSite: 'เว็บไซต์หลัก', teamCodex: 'สมุดทีม', footer: 'WC-MMO สมุดทีม · ภายในเท่านั้น', syncedFrom: 'ซิงก์จาก' },
  englishSource: 'เนื้อหาสเปกเป็นภาษาอังกฤษตามไฟล์ต้นฉบับใน wcmmo-specs',
  common: { all: 'ทั้งหมด', clear: 'ล้าง', search: 'ค้นหา', openOnGithub: 'เปิดใน GitHub ↗', noneYet: 'ยังไม่มี', updated: 'อัปเดต' },
  dash: {
    kicker: 'Action MMORPG ไร้คลาส · Purpur 26.2',
    title: 'WC-MMO Codex',
    intro: 'ทุกสเปก การตัดสินใจ และ PoC จาก',
    intro2: ' อ่านตรงจากรีโป และแสดงความคืบหน้าเป็นกราฟ',
    browse: 'ดูสเปกทั้งหมด',
    graph: 'กราฟความเชื่อมโยง',
    lastCommit: (a: string, b: string) => `คอมมิตสเปกล่าสุด ${a} · ซิงก์ ${b}`,
    slice: 'Vertical slice',
    days: (n: number) => `${n} วัน`,
    toEarly: 'ถึงเส้น 2 สัปดาห์',
    toLate: 'ถึงเส้น 3 สัปดาห์',
    passed: 'เลยกำหนดแล้ว',
    start: 'เริ่ม',
    wk2: '2 สัปดาห์',
    wk3: '3 สัปดาห์',
    dayOf: (d: number, t: number) => `วันที่ ${d} จาก ${t} วัน ทบทวนขอบเขตงานตอนจบสัปดาห์แรก (TM3)`,
    tiles: { specsDone: 'สเปกที่เสร็จ', decisions: 'ตัดสินใจแล้ว', stillOpen: (n: number) => `ยังเปิดอยู่ ${n}`, pocs: 'PoC ที่ผ่าน', acceptance: 'เกณฑ์ตรวจรับ', questions: 'คำถามถึงเจ้าของ', pending: 'รอคำตอบ' },
    pipeline: 'สายพานสเปก',
    allSpecs: 'สเปกทั้งหมด →',
    pipelineHelp1: 'DRAFT → READY → IN-PROGRESS → DONE สเปกจะขึ้นเป็น READY ไม่ได้ถ้ายังมีการตัดสินใจที่อ้างถึงค้างอยู่ ตัวเลขข้างแต่ละ draft คือจำนวนสิ่งที่ขวางอยู่',
    pipelineHelp2: (n: number) => `มี ${n} draft ที่ไม่มีการตัดสินใจค้าง เหลือแค่เขียนส่วนที่ขาดให้ครบ`,
    open: (n: number) => `ค้าง ${n}`,
    unblocked: 'ไม่มีอะไรขวาง',
    byArea: 'การตัดสินใจแยกตามหมวด',
    decisionsLink: 'การตัดสินใจ →',
    blocks: 'อะไรขวางแต่ละสเปก',
    graphLink: 'กราฟ →',
    blocksHelp: 'จำนวนการตัดสินใจที่ยังเปิดอยู่ ซึ่งแต่ละสเปกที่ยังไม่เสร็จอ้างถึง คลิกแท่งเพื่อเปิดสเปก',
    phases: 'เฟส',
    roadmapLink: 'โรดแมป →',
    phase: (n: number, name: string) => `เฟส ${n}: ${name}`,
    nSpecs: (n: number) => `${n} สเปก`,
    notSpecced: 'ยังไม่มีสเปก',
    pocs: 'PoC ของเฟส 0',
    activity: 'ความเคลื่อนไหวของรีโปสเปก',
    recent: 'ล่าสุด',
    commit: 'คอมมิต',
    decision: 'ตัดสินใจ',
    lastSynced: (d: string) => `ซิงก์รีโปสเปกล่าสุด ${d}`,
  },
  charts: { decided: 'ตัดสินใจแล้ว', partly: 'บางส่วน / กำลังทดสอบ', open: 'ยังเปิดอยู่', blocking: 'ที่ขวางอยู่', openDecisions: ' การตัดสินใจที่ค้าง', added: 'บรรทัดที่เพิ่ม', removed: 'บรรทัดที่ลบ' },
  specs: {
    kicker: 'สมุดเควสต์',
    title: 'สเปก',
    intro1: 'หนึ่งการ์ดต่อหนึ่งไฟล์',
    intro2: ' ตัวกรองจะอยู่ใน URL จึงแชร์มุมมองให้คนอื่นได้',
    placeholder: 'ชื่อ เรื่องราว รีโป D-xx…',
    status: 'สถานะ',
    phase: 'เฟส',
    repo: 'รีโป',
    blocked: 'ถูกขวาง',
    hasOpen: 'มีการตัดสินใจค้าง',
    unblocked: 'ไม่มีอะไรขวาง',
    count: (n: number, t: number) => `${n} จาก ${t} สเปก`,
    none: 'ไม่มีสเปกที่ตรงกับตัวกรองนี้',
    blockedBy: (n: number) => `ถูกขวางโดยการตัดสินใจที่ค้าง ${n} ข้อ`,
    openQ: (n: number) => `คำถามค้าง ${n}`,
    acceptance: 'เกณฑ์ตรวจรับ',
  },
  spec: {
    doneMeans: 'ถือว่าเสร็จเมื่อ:',
    phase: 'เฟส',
    repos: 'รีโปเป้าหมาย',
    fire: 'โหมด FIRE',
    acceptance: 'เกณฑ์ตรวจรับ',
    log: 'บันทึกการสร้าง',
    runs: (n: number) => `บันทึกแล้ว ${n} รอบ`,
    notBuilt: 'ยังไม่ได้เริ่มสร้าง',
    lastChange: 'แก้ไขล่าสุด',
    decisions: 'การตัดสินใจ',
    nOpen: (n: number) => `(ค้าง ${n})`,
    pocs: 'PoC',
    linked: 'สเปกที่เกี่ยวข้อง',
    mentions: 'อ้างถึง',
    mentionedBy: 'ถูกอ้างถึงโดย',
  },
  phases: { foundation: 'รากฐาน', unphased: 'ยังไม่จัดเฟส', phase: (n: number, name: string) => `เฟส ${n}: ${name}` },
  decisions: {
    kicker: 'GDD v2',
    title: 'การตัดสินใจ',
    intro: 'ทุก D-xx ในเอกสารดีไซน์ พร้อมคำแนะนำ การตัดสินของเจ้าของ และสเปกที่ขึ้นกับมัน สเปกจะขึ้นเป็น READY ไม่ได้ถ้าการตัดสินใจที่อ้างถึงยังเปิดอยู่',
    search: 'ค้นหาการตัดสินใจ…',
    options: 'ตัวเลือก: ',
    recommendation: 'คำแนะนำ · ',
    ownersCall: 'เจ้าของตัดสิน · ',
    status: 'สถานะ: ',
    citedBy: 'อ้างถึงโดย',
    none: 'ไม่มีการตัดสินใจที่ตรงกัน',
    log: 'บันทึกการตัดสินใจ',
  },
  graph: {
    kicker: 'แผนที่งาน',
    title: 'กราฟความเชื่อมโยง',
    intro: 'เฟส → สเปก → การตัดสินใจที่สเปกอ้างถึง → PoC ที่ใช้ตัดสิน เส้นประที่เคลื่อนไหวคือการตัดสินใจที่ยังเปิดอยู่ คลิกการ์ดเพื่อดูความเชื่อมโยง เลื่อนเพื่อแพน ถ่างนิ้วหรือกด ⌘/Ctrl + เลื่อนเพื่อซูม',
    legend: { done: 'เสร็จ / ตัดสินแล้ว / ผ่าน', open: 'ร่าง / ยังเปิด', partly: 'บางส่วน', testing: 'กำลังทดสอบ / แผนสำรอง', pending: 'PoC ที่รอทดสอบ' },
    openOnly: 'เฉพาะที่ยังเปิดอยู่',
    clear: 'ล้างการเลือก',
    columns: 'คอลัมน์',
    col1: 'เฟสจากสเปก 004',
    col2: 'สเปก แยกสีตามสถานะ',
    col3: (a: number, b: number) => `การตัดสินใจที่ถูกอ้างถึง (${a} จาก ${b})`,
    col4: 'PoC เฟส 0 ที่ใช้ตัดสิน',
    select: 'เลือกการ์ดเพื่อดูรายละเอียดและสิ่งที่เชื่อมอยู่',
    blocksReady: (n: number) => (n ? `มีการตัดสินใจค้าง ${n} ข้อที่ขวาง READY` : 'ไม่มีการตัดสินใจค้าง'),
    openSpec: 'เปิดสเปก ▶',
    openDecision: 'เปิดการตัดสินใจ ▶',
    roadmap: 'โรดแมป ▶',
    pass: 'ผ่านเมื่อ: ',
    nSpecs: (n: number) => `${n} สเปก`,
    loading: 'กำลังโหลดกราฟ…',
  },
  roadmap: {
    kicker: 'สเปก 004',
    title: 'โรดแมป',
    intro1: 'พิสูจน์เทคโนโลยีที่เสี่ยงก่อน (เฟส 0) แล้วส่งมอบเวอร์ชันเล็กที่เล่นได้ ข้อมูลทั้งหมดอ่านมาจาก',
    window: 'ช่วงเวลา Vertical slice',
    today: 'วันนี้',
    recheck: 'ทบทวนขอบเขต',
    legend: 'กรอบทอง = วันนี้ · ขีดส้ม = ทบทวนขอบเขตตอนจบสัปดาห์แรก (TM3) · เขียว = เป้า 2 สัปดาห์ ทอง = ขยายถึง 3 สัปดาห์',
    phases: 'เฟส',
    phase: (n: number) => `เฟส ${n}`,
    exit: 'เงื่อนไขจบเฟส: ',
    notSpecced: 'ยังไม่มีสเปก',
    pocs: 'PoC ของเฟส 0',
    passWhen: 'ผ่านเมื่อ',
    fallback: 'แผนสำรอง',
    notes: (d: string) => `บันทึกผล (${d})`,
    prereqs: 'สิ่งที่ต้องมีก่อนเริ่ม PoC',
    progress: 'บันทึกความคืบหน้าและขั้นต่อไป',
  },
  questions: {
    title: 'คำถามที่ค้างอยู่',
    intro: 'สิ่งที่ทีมกำลังรอ เมื่อได้คำตอบ จะย้ายไปที่ "ตอบแล้ว" จากนั้นอัปเดตการตัดสินใจใน GDD แล้วจึงอัปเดตสเปกที่อ้างถึง',
    pending: (n: number) => `รอ ${n}`,
    answered: 'ตอบแล้ว',
    pluginFill: 'ข้อมูลปลั๊กอินที่ยังต้องกรอก',
    pluginsLink: 'ปลั๊กอิน →',
    answeredTitle: 'ตอบแล้ว',
    total: (n: number) => `มีคำถามรอคำตอบทั้งหมด ${n} ข้อ`,
  },
  plugins: {
    title: 'ปลั๊กอิน',
    intro1: 'ปลั๊กอินทั้งหมดของเซิร์ฟเวอร์และสถานะของแต่ละตัว รายละเอียดเต็มอยู่ใน',
    guide: 'คู่มือปลั๊กอิน',
    headers: ['ปลั๊กอิน', 'หมวด', 'สถานะ', 'เวอร์ชัน', '26.2', 'ใช้ทำอะไร', 'สเปก'],
    legend: '26.2: ✅ หน้าร้านระบุว่ารองรับ 26.2 · ❓ ยังไม่ยืนยัน · ⚠️ หน้าร้านระบุเวอร์ชันสูงสุดที่เก่ากว่า',
  },
  library: {
    kicker: 'ห้องอ่านหนังสือ',
    title: 'คลังเอกสาร',
    intro: 'เอกสารดีไซน์ บรีฟ ทะเบียน และ ADR แสดงผลจากรีโปสเปก',
    groups: { Design: 'ดีไซน์', Brief: 'บรีฟ', Registry: 'ทะเบียน', ADR: 'การตัดสินใจด้านสถาปัตยกรรม' },
    specsLive: (n: number) => `สเปกทั้ง ${n} ไฟล์อยู่ที่หน้า`,
    note: (n: string) =>
      `เอกสารนี้${({ 'superseded by v2': 'ถูกแทนที่ด้วย v2 แล้ว', 'full spoilers, team only': 'มีสปอยล์เต็ม สำหรับทีมเท่านั้น' } as Record<string, string>)[n] ?? n}`,
    boards: 'บอร์ดคอนเซ็ปต์',
  },
  notFound: { title: 'ทางนี้พาไปสู่ความว่างเปล่า', body: 'ไม่พบหน้าหรือสเปกนี้ในรีโปสเปกที่ซิงก์มา', back: 'กลับไปที่ Codex' },
}

export const strings: Dict<Strings> = { en, th }
